# -*- coding: utf-8 -*-
"""Hires_ember_quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x14G1EYjwNyiJu7t7uiw3sdfH3ztBhxQ

1. cella – Könyvtárak telepítése
"""

!pip install -U openai langchain langchain-openai langsmith

"""2. cella – API kulcsok beállítása (IDE ÍROD BE A SAJÁT KULCSAIDAT)"""

#
OPENAI_API_KEY = "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"
LANGSMITH_API_KEY = "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"

import os
import langsmith # Added to enable Langsmith auto-patching

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

os.environ["LANGSMITH_API_KEY"] = LANGSMITH_API_KEY
os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGSMITH_PROJECT"] = "hires-ember-quiz"

"""3. cella – OpenAI kliens + segédfüggvények"""

#  from openai import OpenAI
# client = OpenAI()


import openai
from langsmith import traceable
from langsmith.wrappers import wrap_openai

client = wrap_openai(openai.Client())







def keres_hires_ember(nev):
    """OpenAI-val lekérdezi a ismert ember adatait."""
    prompt = f"""
A feladatod: egy ismert személy adatait kell visszaadnod.
A név lehet magyar vagy külföldi híresség is.
Kiemelten kezeld a magyar hírességeket, például:
- sportolók: Puskás Ferenc, Egerszegi Krisztina, Hosszú Katinka, Dzsudzsák Balázs
- zenészek: Freddie Mercury, Presser Gábor, Ákos, Korda György
- tudósok: Szent-Györgyi Albert, Neumann János, Teller Ede
- írók: Kertész Imre, Márai Sándor, József Attila
- közéleti szereplők: Rubik Ernő, Gábor Dénes
- Használd a Wikipedia adatait

    A felhasználó ezt a nevet adta meg: {nev}

    Add vissza az alábbi mezőket:
    - Név (helyes, teljes név)
    - Születési idő
    - Születési város
    - Születési ország
    - Foglalkozás / tevékenység (pl. fizikus, festő, színész, sportoló + sportág)

    Ha NEM létező vagy nem híres személyt adtak meg:
    VÁLASZ: "Nem találtam adatot az általad megadott személyről."

    Ne találj ki adatot, ne hallucinálj.
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    return response.choices[0].message.content

"""4. cella – Kvíz generálása"""

def generalj_kviz_kerdesenkent():
    prompt = """
    Készíts egy 10 éves gyermekeknek szóló, 10 kérdésből álló híres ember kvízt.
    Legyenek benne 30%-ban magyar híres emberek és 70%-ban nem magyar híres emberek is.
     név lehet magyar vagy külföldi híresség is.
  Kiemelten kezeld a magyar hírességeket, például:
  -  sportolók: Puskás Ferenc, Egerszegi Krisztina, Hosszú Katinka, Dzsudzsák Balázs
  - zenészek: Freddie Mercury, Presser Gábor, Ákos, Korda György
  - tudósok: Szent-Györgyi Albert, Neumann János, Teller Ede
  - írók: Kertész Imre, Márai Sándor, József Attila
  - közéleti szereplők: Rubik Ernő, Gábor Dénes

    Minden kérdés:
    - Tartalmazza a híres ember nevét
    - A kérdés vagy a születési országra, vagy a foglalkozásra kérdezzen rá
    - Legyen pontosan 4 válaszlehetőség: 1) 2) 3) 4)
    - Add meg a helyes választ szám formájában (1 -4)

    A kimenet formátuma legyen:

    1. Kérdés szövege
    1) ...
    2) ...
    3) ...
    4) ...
    Helyes válasz: X

    (és így tovább 10 kérdésig)
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )

    return response.choices[0].message.content

"""5. cella – Kvíz futtatása és értékelése"""

def futtasd_kviz_kerdesenkent():
    kviz = generalj_kviz_kerdesenkent()
    sorok = kviz.split("\n")

    kerdesek = []
    aktualis = []

    for sor in sorok:
        if sor.strip().startswith("Helyes válasz:"):
            aktualis.append(sor)
            kerdesek.append(aktualis)
            aktualis = []
        else:
            if sor.strip():
                aktualis.append(sor)

    pont = 0

    print("\n=== Híres ember kvíz ===\n")

    for i, kerdes in enumerate(kerdesek):
        print(f"\n--- {i+1}. kérdés ---")

        for sor in kerdes[:-1]:
            print(sor)

        helyes = kerdes[-1].split(":")[1].strip()

        valasz = None
        while valasz not in ["1", "2","3","4"]:
            valasz = input("Válasz (1 - 4): ").strip()

        if valasz == helyes:
            print("✔️ Helyes!")
            pont += 1
        else:
            print(f"❌ Nem jó. A helyes válasz: {helyes}")

    print("\n=== Eredmény ===")
    print(f"Pontszám: {pont}/10")

    if pont >= 9:
        print("Fantasztikus teljesítmény!")
    elif pont >= 6:
        print("Ügyes vagy!")
    elif pont >= 4:
        print("Ezt még gyakorolnod kell!")
    else:
        print("Csinálj inkább cigánykereket 😉!")

"""6. cella – Fő program (menü + logika)"""

def main():
    while True:
        print("\nÜdvözöllek a híres ember kvízben.")
        print("1) Gyakorlás")
        print("2) Kvíz")
        print("3) Kilépés")

        valasztas = None
        while valasztas not in ["1", "2", "3"]:
            valasztas = input("Válassz (1-3): ").strip()

        # --- GYAKORLÁS ---
        if valasztas == "1":
            while True:
                nev = input("\nAdd meg egy híres ember nevét: ")
                eredmeny = keres_hires_ember(nev)
                print("\n" + eredmeny)

                print("\nSzeretnél még gyakorolni?")
                print("1) Igen")
                print("2) Nem")

                ujra = None
                while ujra not in ["1", "2"]:
                    ujra = input("Válassz (1-2): ").strip()

                if ujra == "2":
                    break

        # --- KVÍZ ---
        elif valasztas == "2":
            futtasd_kviz_kerdesenkent()

            print("\nSzeretnél új kvízt?")
            print("1) Igen")
            print("2) Nem")

            uj_kviz = None
            while uj_kviz not in ["1", "2"]:
                uj_kviz = input("Válassz (1-2): ").strip()

            if uj_kviz == "1":
                continue  # új kvíz indul
            else:
                pass  # vissza a főmenübe

        # --- KILÉPÉS ---
        elif valasztas == "3":
            print("Viszlát!")
            break

        # --- FŐMENÜBE VISSZA ---
        print("\nVisszatérsz a főmenübe?")
        print("1) Igen")
        print("2) Nem")

        vissza = None
        while vissza not in ["1", "2"]:
            vissza = input("Válassz (1-2): ").strip()

        if vissza == "2":
            print("Viszlát!")
            break

main()









